config/routes.rb
Railsgirls::Application.routes.draw do
  devise_for :users
  get "pages/info"
  get "pages/touchdown"
  get "static/touchdown2"
  resources :ideas
  root 'pages#info'

  

end

app/models/idea.rb
class Idea < ActiveRecord::Base
	mount_uploader :picture, PictureUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :nickname
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render action: 'show', status: :created, location: @idea }
      else
        format.html { render action: 'new' }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end

  def touchdown
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def touchdown2
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1 class="friend">Everything that Matters</h1>

    <% @ideas.each do |idea| %>
       <p>
        <%= idea.name %>
        <%= idea.description %>
        <%= idea.picture %>
        <%= link_to 'Show', idea %>
        <%= link_to 'Edit', edit_idea_path(idea) %>
        <%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %>
        </p></br>

    <% end %>




<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @idea.picture %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Breezy on Rails</title>
  <link rel="stylesheet" href="http://railsgirls.com/assets/bootstrap.css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
	      <a class="brand" href="/">Breezy on Rails</a>
	      <ul class="nav">
	        <li class="active"><a href="/ideas">Ideas</a></li>
	        <% if user_signed_in? %>
	        	<li class="active"><%= link_to "Logout", destroy_user_session_path, :method => "delete" %></li>
	        	<li class="active">Hi, <%= current_user.email %></li>
	        <% else %>
	        	<li class="active"><%= link_to "Sigh Up", new_user_registration_path %></li>
	        	<li class="active"><%= link_to "Sigh In", new_user_session_path %></li>
	        <% end %>
	      </ul>
	    </div>
	  </div>
	</div>



	<div class="container">
		<% if notice %>
			  <p class="alert alert-notice"><%= notice %></p>
			<% end %>
			<% if alert %>
			  <p class="alert alert-error"><%= alert %></p>
		<% end %>
		<%= yield %>
	</div>
<footer>
  <div class="container friend">
    Rails bootcamp
  </div>
</footer>

</body>

</html>

app/views/layouts/static.erb
<!DOCTYPE html>
<html>
<head>
	<title>Today is Football Saturday</title>
	<style type="text/css" media="screen">
	.soot{
		color:black;
		width:20%;
		height:50px;
		background-color:blue
	}
		table#football{
			border:5px solid blue;
			width:600;
			height:400;
		}
	</style>


</head>
<body>
	
	<div class="container">
		<%= yield %>
	</div>
<footer>
  <div class="container friend">
    Breezy Stuff
  </div>
</footer>

</body>

</html>

app/views/pages/info.html.erb
<h1>This is Bryanne</h1>
<p>I was born in Toronto. I live in Nairobi.</p>
<%=link_to 'Back to the Future', ideas_path %>
<a href='/ideas', target='_blank'>Open New Tab</a>

app/views/pages/touchdown2.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Today is Football Saturday</title>
	<style type="text/css" media="screen">
	.soot{
		color:black;
		width:20%;
		height:50px;
		background-color:blue
	}
		table#football{
			border:5px solid blue;
			width:600;
			height:400;
		}
	</style>


</head>
<body>
	
<div style="color:blue; width:100%;">
	<div class="soot">
		I want to watch sports.
	</div>
	<div>
		<img src="https://fbcdn-sphotos-b-a.akamaihd.net/hphotos-ak-frc3/1468685_10100328623748070_963439592_n.jpg" style="width:265px; height:265px" alt="picture broken">
	</div>
	<div style="color:black; width:20%; height:300px; background-color: grey;">
		The quarterback got sacked.<br/>
		<img src="./canada.jpg" style="width:200px; height:200px" alt="canada photo did not work">
	</div>
	<div style="color:blue; width:30%; height:350px; background-color: pink;">
		<img src="https://fbcdn-sphotos-g-a.akamaihd.net/hphotos-ak-prn2/1374847_10100797328818453_683421194_n.jpg" style="width:300px; height:300px" alt="picture broken">
	</div>
	<table id="football">
		<caption>famous football player stats</caption>
		<thead>
			<tr>
				<th>measurement</th>
				<th>john elway</th>
				<th>andrew luck</th>
				<th>RG3</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>speed</td>
				<td>18sec</td>
				<td>20sec</td>
				<td>3sec</td>
			</tr>
			<tr>
				<td>weight</td>
				<td>152lbs</td>
				<td>130lbs</td>
				<td>300lbs</td>
			</tr>
			<tr>
				<td>age</td>
				<td>40</td>
				<td>28</td>
				<td>22</td>
			</tr>
		</tbody>
	</table>
</div>
</body>

</html>